In [1]:
import numpy as np

A = np.array([[2, 1], [1, 2]])
print(A)

B = np.array([[1, 1], [1, 1.0001]])
print(B)

cond_A = np.linalg.cond(A)
print(cond_A)

cond_B = np.linalg.cond(B)
print(cond_B)

invA = np.linalg.inv(A)
print(invA)

invB = np.linalg.inv(B)
print(invB)

print(np.linalg.norm(A) * np.linalg.norm(invA))
print(np.linalg.norm(B) * np.linalg.norm(invB))


[[2 1]
 [1 2]]
[[1.     1.    ]
 [1.     1.0001]]
2.999999999999999
40002.000074915224
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[ 10001. -10000.]
 [-10000.  10000.]]
3.333333333333334
40002.00010000441
